**Course**: Data Visualization (Prof. Dr. Heike Leitte, Luisa Vollmer, RPTU Kaiserslautern),   **Name**: Leyla B. Akıncı,   **Date**: 03.12.2023

<div class="alert alert-info">
    
# Assignment 2 - Good Chart Design
</div>

The **goals** of the second assignment are:
- Practice visualization design critiques using a given visualization.
- Decompose a given chart into its components and analyze their design.
- Practice visual encoding theory by detecting marks and channels.
- Design an information rich chart.

To achieve these goals, your task is to analyze, critique, and revise a given visualization that depicts the received and handled tickets (technical issues).

<div class="alert alert-danger">

**Important**: While no points will be awarded for typing the correct answers in the notebooks, it is highly advised to solve the tasks thoroughly. They are designed to be encouraging and provide you with valuable learnings for the exam, understanding of the methods and practical coding.
</div>

<div class="alert alert-success">
    
All tasks in this notebook are marked in green.
</div>

<div class="alert alert-info">

## 1. Scenario and Starter Code
</div>

Imagine that you manage an information technology (IT) team. Your team receives tickets, or technical issues, from employees. In the past year, you've had two team members leave and decided at the time not to replace them. You have heard a rumbling of complaints from the remaining employees about having to "pick up the slack". You've just been asked about your hiring needs for the coming year and are wondering if you should hire a couple more people. First, you want to understand what impact the departure of individuals over the past year has had on your team's overall productivity. You plot the monthly trend of incoming tickets and those processed over the past calender year. You see that there is some evidence your team's productivity is suffering from being short-staffed and now want to turn the quick-and-dirty visual you created into the basis for your hiring request.

Below is the code and chart of the initial ticket visualization. Read through the code and make sure that you understand it.

In [1]:
import pandas as pd
from bokeh.plotting import figure, output_notebook, show
from bokeh.models import ColumnDataSource, LabelSet, SingleIntervalTicker, Legend, Scatter #DatetimeTickFormatter
from bokeh.transform import dodge
#from bokeh.models.tickers import MonthsTicker

output_notebook()

In [2]:
month = [i for i in range(1,13)]
received = [160,184,241,149,180,161,132,202,160,139,149,177]
processed = [160,184,237,148,181,150,123,156,126,121,124,140]

df = pd.DataFrame({'month': month, 
                   'received': received, 
                   'processed': processed})
df.head()

   month  received  processed
0      1       160        160
1      2       184        184
2      3       241        237
3      4       149        148
4      5       180        181

In [3]:
p = figure(title="TICKET TREND", height=400)
p.vbar(source=df, x=dodge('month', -0.175, range=p.x_range), top='received', width=0.3, 
       legend_label="Ticket Volume Received")
p.vbar(source=df, x=dodge('month',  0.175, range=p.x_range), top='processed', width=0.3, 
       color="deeppink", legend_label="Ticket Volume Processed")

# remove the toolbar
p.toolbar.logo = None
p.toolbar_location = None

show(p)

<div class="alert alert-info">
    
## 2. Analysis of the original chart
</div>

### Message

<div class="alert alert-success">
    
Write down the message you want to convey with your chart
    
</div>

<div class="alert alert-warning">

I want to show the effects of staff-shortage on the productivity of IT team. As a measure of productivity I want to utilize the number of tickets received and also the number of tickets processed by the IT team over the course of a year. Specifically, I want to show the difference between these two measures as a representation of the effectivenes of my IT team.
</div>

### Design critique

<div class="alert alert-success">
   
- How good does the current design support the message your trying to make?
- Can you spot problems with the current design?
    
</div>

<div class="alert alert-warning">

Current design provides the basic information that allows making inferences about the issue, such as value of tickets received and processed in each month of the year. However it needs more context to communicate the idea easily with everyone whether they have many or few information about the issue. The graph seems to not communicate with the observer. There are a couple of data it presents but without having a rich background information (like the one you provided us as "scenario") it is hard to extract meaning from it. To make it better we can work on the x axis labels, the title as well as the presentation of data to facilitate information.

</div>

### Analyze the chart design
Now go through each of the elements of the chart and check if the design is suitable. 

<div class="alert alert-success">
    
Make a list of all visible elements of the chart and problems with the design.
    
</div>

<div class="alert alert-warning">

* More context:
    * X axis ticks: Instead of using numbers, using the actual or abbreviated names of the months would make the graph easier to comprehend for those people who will be presented with this data for the first time (such as the decision makers).
    * Title: The title could be changed something like "Received and Processed Ticket Numbers by IT Department 2023" which would carry more context.
* Facilitating information:
    * A derived measure: Having information about received and processed ticket numbers is a good start. But according to our goals we can derive a measure from these two, to be more clear while trying to get the message across. What should be the emphasis here? That the IT department cannot adress all the tickets received? Or maybe the products, produced by the IT department, started to get increasingly more tickets as a result of staff-shortage?Either case, the graph can do much better than providing the elementary data.

</div>

<div class="alert alert-info">
    
## 3. Improved design of helper elements
</div>

A major problem of the current chart is that it is too cluttered and full of competing information.
<div class="alert alert-success">
    
Improve all chart elements of the list above except for the data representation (bar elements) to achieve a better "background" design.

</div>

In [4]:
p = figure(title="Received and Processed Ticket Numbers by IT Department in 2023", height=400)  ###Changing title###
p.vbar(source=df, x=dodge('month', -0.175, range=p.x_range), top='received', width=0.3, 
       legend_label="Ticket Volume Received")
p.vbar(source=df, x=dodge('month',  0.175, range=p.x_range), top='processed', width=0.3, 
       color="deeppink", legend_label="Ticket Volume Processed")

#Changing x axis ticks
p.xaxis.ticker = SingleIntervalTicker(interval=1) #Making ticks go from 1 to 12 with an interval of 1
month_names = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] #list of month names
p.xaxis.major_label_overrides = {i: month for i, month in enumerate(month_names,1)} #A dictionary that matches the numeric values with month names


#Changing title (continue)
p.title.align = "center"
p.title.text_font_size = "12pt"
    

#remove the toolbar
p.toolbar.logo = None
p.toolbar_location = None
show(p)

<div class="alert alert-info">
    
## 4. Data Encoding
</div>

### Marks and channels

<div class="alert alert-success"> What are the marks and channels used to encode data? Write down the information as discussed in the lecture. </div>

<div class="alert alert-warning">
    
* **Marks** : An area-type mark is used in the form of boxes that extend regarding the values observed on a certain month.
* **Channels** : Hue is used as a channel to differentiate two different data, tickets received and tickets processed.  

</div>

### Creating new columns

The current dataframe only contains the raw data. Often you need to process the data further to obtain suitable input for your data. Read the [ten minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html#min) introduction to pandas programming.

Now you are able to do the following dataframe operations:

In [5]:
import numpy as np

a = [int(i*10) for i in np.random.random(6)]
b = [int(i*10) for i in np.random.random(6)]

df_test = pd.DataFrame({"A": a, "B": b})

# select a column
df_test['A']

# create a new column by adding two column
df_test['A+B'] = df_test['A'] + df_test['B']

# create a new column by applying a function to an existing column
df_test['A+1'] = df_test['A'].apply(lambda x: x+1)
df_test['Size(A)'] = df_test['A'].apply(lambda x: "S" if x < 5 else "M")

df_test

   A  B  A+B  A+1 Size(A)
0  7  9   16    8       M
1  2  7    9    3       S
2  4  1    5    5       S
3  9  0    9   10       M
4  8  0    8    9       M
5  3  8   11    4       S

<div class="alert alert-success"> 
    
Use these dataframe operations to create the following columns in the ticket dataframe:
- the difference between received and processed tickets
- the total number of open tickets, i.e., the sum of all tickets that have not been handled yet. See method [`cumsum()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.cumsum.html) for a pandas Series.
    
</div>

In [6]:
#a new variable that has values of monthly differences between received and processed tickets
df["diff"] = df["received"] - df["processed"]

#a new variable that has values of overall open tickets which grows (or shrinks) cumulatively each month depending on the diff values of past month
df["overall_optickets"] = df["diff"].cumsum()

df

    month  received  processed  diff  overall_optickets
0       1       160        160     0                  0
1       2       184        184     0                  0
2       3       241        237     4                  4
3       4       149        148     1                  5
4       5       180        181    -1                  4
5       6       161        150    11                 15
6       7       132        123     9                 24
7       8       202        156    46                 70
8       9       160        126    34                104
9      10       139        121    18                122
10     11       149        124    25                147
11     12       177        140    37                184

### Alternative data encodings
<div class="alert alert-success"> Now change the presentation of the data. Select two new, suitable chart types for the ticket data. Stick to chart types that use the same x- and y-axis as defined above. Implement (at least) two different data encodings. What is your favorite? </div>

In [7]:
#Creating a function that will generate a line chart with our new variables
def line_chart():
    p = figure(title="Differences Between Received and Processed Tickets 2023", height=400, y_range=(-10, 200))

    p.line(source=df, x='month', y='diff', legend_label="Number of Open Tickets", line_alpha=0.8, line_width=2.5)
    p.line(source=df, x='month', y='overall_optickets', legend_label="Cumulative Number of Open Tickets", color="deeppink", line_width=2.5)
    
    #styling
    p.xaxis.ticker = SingleIntervalTicker(interval=1)
    p.xaxis.major_label_overrides = {i: month for i, month in enumerate(month_names,1)}
    p.legend.location = "top_left"
    p.title.align = "center"
    p.title.text_font_size = "12pt"
    p.xaxis.ticker.num_minor_ticks = 0
    
    return p

p_1 = line_chart()
show(p_1)

In [8]:
#Another function that combines a boxplot for sheer values and a line for cumulative values.
def combined_chart():
    p = figure(title="Differences Between Received and Processed Tickets 2023", height=400, y_range=(-10, 200), x_range=(0.60,12.60))

    p.vbar(source=df, x='month', top='diff', width=0.95, legend_label="Number of Open Tickets")
    p.line(source=df, x='month', y='overall_optickets', legend_label="Cumulative Number of Open Tickets", color="deeppink", line_width=2.5)
        
    #styling
    p.xaxis.ticker = SingleIntervalTicker(interval=1)
    p.xaxis.major_label_overrides = {i: month for i, month in enumerate(month_names,1)}
    p.legend.location = "top_left"
    p.title.align = "center"
    p.title.text_font_size = "12pt"
    p.xaxis.ticker.num_minor_ticks = 0
    
    return p

p_2 = combined_chart()
show(p_2)

<div class="alert alert-info"> 
    
## 5. Revise the chart 
</div>

<div class="alert alert-success"> 
    
Now combine the results from the previous steps and create a final chart that you would send to your boss to ask for additional staff. Also think about adding additional information to your chart with labels etc.
</div>

In [9]:
#Final decision 
def combined_chart():
    p = figure(title="Differences Between Received and Processed Tickets 2023", height=400, y_range=(-10, 200), x_range=(0.60,12.60))

    p.vbar(source=df, x='month', top='diff', width=0.95, legend_label="Number of Open Tickets")
    p.line(source=df, x='month', y='overall_optickets', legend_label="Cumulative Number of Open Tickets", color="deeppink", line_width=2.5)
        
    #styling
    p.xaxis.ticker = SingleIntervalTicker(interval=1)
    p.xaxis.major_label_overrides = {i: month for i, month in enumerate(month_names,1)}
    p.legend.location = "top_left"
    p.title.align = "center"
    p.title.text_font_size = "12pt"
    p.xaxis.ticker.num_minor_ticks = 0
    p.toolbar.logo = None
    p.toolbar_location = None
    
    return p

p_2 = combined_chart()
show(p_2)

   *The number of tickets that cannot be adressed effectively by the IT department in each month\
   of 2023 and their cumulative increase over the year.*

**Caption**:

As we learned: Each figure needs a caption. <div class="alert alert-success"> Write a caption for your figure. Position it underneath your chart so you can take a screenshot of chart + caption. </div>

The number of tickets that cannot be adressed effectively by the IT department in each month of 2023 and their cumulative increase over the year.